### ISSUE TITLE
data block within resource wrongly detected as data source

### ISSUE THREAD

**Issue by dod38fr** [emacsorphanage/terraform-mode#48]
Hi

Resource `kubernetes_secret` requires a data parameter. This parameter is wrongly detected as a data source.

For instance:
```hcl
resource "kubernetes_secret" "wildcard-cert" {
  data = {
    "tls.key" = file(var.wildcard-tls-key-file)
    "tls.crt" = file(var.wildcard-tls-crt-file)
  }

  type = "kubernetes.io/tls"
}
```

This triggers the creation of `=/{` entry in menu Terraform -> data.

This also shows up in speedbar (with other similar errors):
![2022-11-16_11-02](https://user-images.githubusercontent.com/1110441/202150506-1875b51b-d174-4b5a-8f68-d4b09d631c8b.png)

**Comment by rnikoopour** [comment]
Hey there,

This one is a hard fix. 

Since there's the highlighting component that controls the `data = {` construct is in `hcl-mode` it will be hard to fix up in `terraform-mode`.

We take precedence for the terraform syntax highlighting by placing them earlier in the evaluation chain. 

I took a quick stab at fixing it and wasn't able to.  I'd be happy if anyone had suggestions on how to fix this.

**Comment by dod38fr** [comment]
Thanks  ! :smiley:
